version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-107-22-160-102.compute-1.amazonaws.com
            database: dbr6lqrb342g7o
            schema: public
            user: gdbxdbtnueyerj
            password: 0e1e6750a3d5f08de4df211bcc7b49d82996bd93c3d0d83d444f76fab669de7a
            ssl: true
            rawAccess: true
            port: '5432'
            migrations: true
